#' Define column types for data reading
#'
#' @param ins Character, the instrument
#' @param type Character, fixed or adaptive
#' @param date_format Specification how to read the date field
#' @param datetime_format Specification how to read the datetime field
define_col <- function(ins = c("sf", "lf"),
                       type = c("fixed", "adaptive"),
                       date_format = "",
                       datetime_format = "") {
  ins <- match.arg(ins)
  type <- match.arg(type)
  if (ins == "sf" && type == "fixed") {
    spec <- cols(
      GSED_ID = col_character(),
      `Ma_SF_Parent ID` = col_character(),
      `Ma_SF_Worker Code` = col_double(),
      `Ma_SF_Vist Type` = col_double(),
      Ma_SF_Location = col_double(),
      Ma_SF_Age = col_double(),
      Ma_SF_AH01 = col_double(),
      Ma_SF_AH02 = col_double(),
      Ma_SF_AH03 = col_double(),
      Ma_SF_AH04 = col_double(),
      Ma_SF_AH05 = col_double(),
      Ma_SF_AH06 = col_double(),
      Ma_SF_AH07 = col_double(),
      Ma_SF_AH08 = col_double(),
      Ma_SF_M01 = col_double(),
      Ma_SF_M02 = col_double(),
      Ma_SF_M03 = col_character(),
      Ma_SF_Date = col_date(format = date_format),
      Ma_SF_Caregiver = col_double(),
      Ma_SF_C01 = col_integer(),
      Ma_SF_C02 = col_integer(),
      Ma_SF_C03 = col_integer(),
      Ma_SF_C04 = col_integer(),
      Ma_SF_C05 = col_integer(),
      Ma_SF_C06 = col_integer(),
      Ma_SF_C07 = col_integer(),
      Ma_SF_C08 = col_integer(),
      Ma_SF_C09 = col_integer(),
      Ma_SF_C10 = col_integer(),
      Ma_SF_C11 = col_integer(),
      Ma_SF_C12 = col_integer(),
      Ma_SF_C13 = col_integer(),
      Ma_SF_C14 = col_integer(),
      Ma_SF_C15 = col_integer(),
      Ma_SF_C16 = col_integer(),
      Ma_SF_C17 = col_integer(),
      Ma_SF_C18 = col_integer(),
      Ma_SF_C19 = col_integer(),
      Ma_SF_C20 = col_integer(),
      Ma_SF_C21 = col_integer(),
      Ma_SF_C22 = col_integer(),
      Ma_SF_C23 = col_integer(),
      Ma_SF_C24 = col_integer(),
      Ma_SF_C25 = col_integer(),
      Ma_SF_C26 = col_integer(),
      Ma_SF_C27 = col_integer(),
      Ma_SF_C28 = col_integer(),
      Ma_SF_C29 = col_integer(),
      Ma_SF_C30 = col_integer(),
      Ma_SF_C31 = col_integer(),
      Ma_SF_C32 = col_integer(),
      Ma_SF_C33 = col_integer(),
      Ma_SF_C34 = col_integer(),
      Ma_SF_C35 = col_integer(),
      Ma_SF_C36 = col_integer(),
      Ma_SF_C37 = col_integer(),
      Ma_SF_C38 = col_integer(),
      Ma_SF_C39 = col_integer(),
      Ma_SF_C40 = col_integer(),
      Ma_SF_C41 = col_integer(),
      Ma_SF_C42 = col_integer(),
      Ma_SF_C43 = col_integer(),
      Ma_SF_C44 = col_integer(),
      Ma_SF_C45 = col_integer(),
      Ma_SF_C46 = col_integer(),
      Ma_SF_C47 = col_integer(),
      Ma_SF_C48 = col_integer(),
      Ma_SF_C49 = col_integer(),
      Ma_SF_C50 = col_integer(),
      Ma_SF_C51 = col_integer(),
      Ma_SF_C52 = col_integer(),
      Ma_SF_C53 = col_integer(),
      Ma_SF_C54 = col_integer(),
      Ma_SF_C55 = col_integer(),
      Ma_SF_C56 = col_integer(),
      Ma_SF_C57 = col_integer(),
      Ma_SF_C58 = col_integer(),
      Ma_SF_C59 = col_integer(),
      Ma_SF_C60 = col_integer(),
      Ma_SF_C61 = col_integer(),
      Ma_SF_C62 = col_integer(),
      Ma_SF_C63 = col_integer(),
      Ma_SF_C64 = col_integer(),
      Ma_SF_C65 = col_integer(),
      Ma_SF_C66 = col_integer(),
      Ma_SF_C67 = col_integer(),
      Ma_SF_C68 = col_integer(),
      Ma_SF_C69 = col_integer(),
      Ma_SF_C70 = col_integer(),
      Ma_SF_C71 = col_integer(),
      Ma_SF_C72 = col_integer(),
      Ma_SF_C73 = col_integer(),
      Ma_SF_C74 = col_integer(),
      Ma_SF_C75 = col_integer(),
      Ma_SF_C76 = col_integer(),
      Ma_SF_C77 = col_integer(),
      Ma_SF_C78 = col_integer(),
      Ma_SF_C79 = col_integer(),
      Ma_SF_C80 = col_integer(),
      Ma_SF_C81 = col_integer(),
      Ma_SF_C82 = col_integer(),
      Ma_SF_C83 = col_integer(),
      Ma_SF_C84 = col_integer(),
      Ma_SF_C85 = col_integer(),
      Ma_SF_C86 = col_integer(),
      Ma_SF_C87 = col_integer(),
      Ma_SF_C88 = col_integer(),
      Ma_SF_C89 = col_integer(),
      Ma_SF_C90 = col_integer(),
      Ma_SF_C91 = col_integer(),
      Ma_SF_C92 = col_integer(),
      Ma_SF_C93 = col_integer(),
      Ma_SF_C94 = col_integer(),
      Ma_SF_C95 = col_integer(),
      Ma_SF_C96 = col_integer(),
      Ma_SF_C97 = col_integer(),
      Ma_SF_C98 = col_integer(),
      Ma_SF_C99 = col_integer(),
      Ma_SF_C100 = col_integer(),
      Ma_SF_C101 = col_integer(),
      Ma_SF_C102 = col_integer(),
      Ma_SF_C103 = col_integer(),
      Ma_SF_C104 = col_integer(),
      Ma_SF_C105 = col_integer(),
      Ma_SF_C106 = col_integer(),
      Ma_SF_C107 = col_integer(),
      Ma_SF_C108 = col_integer(),
      Ma_SF_C109 = col_integer(),
      Ma_SF_C110 = col_integer(),
      Ma_SF_C111 = col_integer(),
      Ma_SF_C112 = col_integer(),
      Ma_SF_C113 = col_integer(),
      Ma_SF_C114 = col_integer(),
      Ma_SF_C115 = col_integer(),
      Ma_SF_C116 = col_integer(),
      Ma_SF_C117 = col_integer(),
      Ma_SF_C118 = col_integer(),
      Ma_SF_C119 = col_integer(),
      Ma_SF_C120 = col_integer(),
      Ma_SF_C121 = col_integer(),
      Ma_SF_C122 = col_integer(),
      Ma_SF_C123 = col_integer(),
      Ma_SF_C124 = col_integer(),
      Ma_SF_C125 = col_integer(),
      Ma_SF_C126 = col_integer(),
      Ma_SF_C127 = col_integer(),
      Ma_SF_C128 = col_integer(),
      Ma_SF_C129 = col_integer(),
      Ma_SF_C130 = col_integer(),
      Ma_SF_C131 = col_integer(),
      Ma_SF_C132 = col_integer(),
      Ma_SF_C133 = col_integer(),
      Ma_SF_C134 = col_integer(),
      Ma_SF_C135 = col_integer(),
      Ma_SF_C136 = col_integer(),
      Ma_SF_C137 = col_integer(),
      Ma_SF_C138 = col_integer(),
      Ma_SF_C139 = col_integer())
  }

  if (ins == "lf" && type == "fixed") {
    spec <- cols(
      GSED_ID = col_character(),
      `Ma_LF_Parent ID` = col_character(),
      `Ma_LF_Worker Code` = col_double(),
      `Ma_LF_Vist Type` = col_double(),
      Ma_LF_Location = col_double(),
      Ma_LF_Age = col_double(),
      Ma_LF_AH01 = col_double(),
      Ma_LF_AH02 = col_double(),
      Ma_LF_AH03 = col_double(),
      Ma_LF_AH04 = col_double(),
      Ma_LF_AH05 = col_double(),
      Ma_LF_AH06 = col_double(),
      Ma_LF_AH07 = col_double(),
      Ma_LF_AH08 = col_double(),
      Ma_LF_M01 = col_double(),
      Ma_LF_M02 = col_double(),
      Ma_LF_M03 = col_character(),
      Ma_LF_Date = col_date(format = date_format),
      Ma_LF_Caregiver = col_double(),
      Ma_LF_A01 = col_integer(),
      Ma_LF_A02 = col_integer(),
      Ma_LF_A03 = col_integer(),
      Ma_LF_A04 = col_integer(),
      Ma_LF_A05 = col_integer(),
      Ma_LF_A06 = col_integer(),
      Ma_LF_A07 = col_integer(),
      Ma_LF_A08 = col_integer(),
      Ma_LF_A09 = col_integer(),
      Ma_LF_A10 = col_integer(),
      Ma_LF_A11 = col_integer(),
      Ma_LF_A12 = col_integer(),
      Ma_LF_A13 = col_integer(),
      Ma_LF_A14 = col_integer(),
      Ma_LF_A15 = col_integer(),
      Ma_LF_A16 = col_integer(),
      Ma_LF_A17 = col_integer(),
      Ma_LF_A18 = col_integer(),
      Ma_LF_A19 = col_integer(),
      Ma_LF_A20 = col_integer(),
      Ma_LF_A21 = col_integer(),
      Ma_LF_A22 = col_integer(),
      Ma_LF_A23 = col_integer(),
      Ma_LF_A24 = col_integer(),
      Ma_LF_A25 = col_integer(),
      Ma_LF_A26 = col_integer(),
      Ma_LF_A27 = col_integer(),
      Ma_LF_A28 = col_integer(),
      Ma_LF_A29 = col_integer(),
      Ma_LF_A30 = col_integer(),
      Ma_LF_A31 = col_integer(),
      Ma_LF_A32 = col_integer(),
      Ma_LF_A33 = col_integer(),
      Ma_LF_A34 = col_integer(),
      Ma_LF_A35 = col_integer(),
      Ma_LF_A36 = col_integer(),
      Ma_LF_A37 = col_integer(),
      Ma_LF_A38 = col_integer(),
      Ma_LF_A39 = col_integer(),
      Ma_LF_A40 = col_integer(),
      Ma_LF_A41 = col_integer(),
      Ma_LF_A42 = col_integer(),
      Ma_LF_A43 = col_integer(),
      Ma_LF_A44 = col_integer(),
      Ma_LF_A45 = col_integer(),
      Ma_LF_A46 = col_integer(),
      Ma_LF_A47 = col_integer(),
      Ma_LF_A48 = col_integer(),
      Ma_LF_A49 = col_integer(),
      Ma_LF_B01 = col_integer(),
      Ma_LF_B02 = col_integer(),
      Ma_LF_B03 = col_integer(),
      Ma_LF_B04 = col_integer(),
      Ma_LF_B05 = col_integer(),
      Ma_LF_B06 = col_integer(),
      Ma_LF_B07 = col_integer(),
      Ma_LF_B08 = col_integer(),
      Ma_LF_B09 = col_integer(),
      Ma_LF_B10 = col_integer(),
      Ma_LF_B11 = col_integer(),
      Ma_LF_B12 = col_integer(),
      Ma_LF_B13 = col_integer(),
      Ma_LF_B14 = col_integer(),
      Ma_LF_B15 = col_integer(),
      Ma_LF_B16 = col_integer(),
      Ma_LF_B17 = col_integer(),
      Ma_LF_B18 = col_integer(),
      Ma_LF_B19 = col_integer(),
      Ma_LF_B20 = col_integer(),
      Ma_LF_B21 = col_integer(),
      Ma_LF_B22 = col_integer(),
      Ma_LF_B23 = col_integer(),
      Ma_LF_B24 = col_integer(),
      Ma_LF_B25 = col_integer(),
      Ma_LF_B26 = col_integer(),
      Ma_LF_B27 = col_integer(),
      Ma_LF_B28 = col_integer(),
      Ma_LF_B29 = col_integer(),
      Ma_LF_B30 = col_integer(),
      Ma_LF_B31 = col_integer(),
      Ma_LF_B32 = col_integer(),
      Ma_LF_B33 = col_integer(),
      Ma_LF_B34 = col_integer(),
      Ma_LF_B35 = col_integer(),
      Ma_LF_B36 = col_integer(),
      Ma_LF_B37 = col_integer(),
      Ma_LF_B38 = col_integer(),
      Ma_LF_B39 = col_integer(),
      Ma_LF_B40 = col_integer(),
      Ma_LF_B41 = col_integer(),
      Ma_LF_B42 = col_integer(),
      Ma_LF_B43 = col_integer(),
      Ma_LF_B44 = col_integer(),
      Ma_LF_B45 = col_integer(),
      Ma_LF_B46 = col_integer(),
      Ma_LF_B47 = col_integer(),
      Ma_LF_B48 = col_integer(),
      Ma_LF_B49 = col_integer(),
      Ma_LF_B50 = col_integer(),
      Ma_LF_B51 = col_integer(),
      Ma_LF_B52 = col_integer(),
      Ma_LF_C01 = col_integer(),
      Ma_LF_C02 = col_integer(),
      Ma_LF_C03 = col_integer(),
      Ma_LF_C04 = col_integer(),
      Ma_LF_C05 = col_integer(),
      Ma_LF_C06 = col_integer(),
      Ma_LF_C07 = col_integer(),
      Ma_LF_C08 = col_integer(),
      Ma_LF_C09 = col_integer(),
      Ma_LF_C10 = col_integer(),
      Ma_LF_C11 = col_integer(),
      Ma_LF_C12 = col_integer(),
      Ma_LF_C13 = col_integer(),
      Ma_LF_C14 = col_integer(),
      Ma_LF_C15 = col_integer(),
      Ma_LF_C16 = col_integer(),
      Ma_LF_C17 = col_integer(),
      Ma_LF_C18 = col_integer(),
      Ma_LF_C19 = col_integer(),
      Ma_LF_C20 = col_integer(),
      Ma_LF_C21 = col_integer(),
      Ma_LF_C22 = col_integer(),
      Ma_LF_C23 = col_integer(),
      Ma_LF_C24 = col_integer(),
      Ma_LF_C25 = col_integer(),
      Ma_LF_C26 = col_integer(),
      Ma_LF_C27 = col_integer(),
      Ma_LF_C28 = col_integer(),
      Ma_LF_C29 = col_integer(),
      Ma_LF_C30 = col_integer(),
      Ma_LF_C31 = col_integer(),
      Ma_LF_C32 = col_integer(),
      Ma_LF_C33 = col_integer(),
      Ma_LF_C34 = col_integer(),
      Ma_LF_C35 = col_integer(),
      Ma_LF_C36 = col_integer(),
      Ma_LF_C37 = col_integer(),
      Ma_LF_C38 = col_integer(),
      Ma_LF_C39 = col_integer(),
      Ma_LF_C40 = col_integer(),
      Ma_LF_C41 = col_integer(),
      Ma_LF_C42 = col_integer(),
      Ma_LF_C43 = col_integer(),
      Ma_LF_C44 = col_integer(),
      Ma_LF_C45 = col_integer(),
      Ma_LF_C46 = col_integer(),
      Ma_LF_C47 = col_integer(),
      Ma_LF_C48 = col_integer(),
      Ma_LF_C49 = col_integer(),
      Ma_LF_C50 = col_integer(),
      Ma_LF_C51 = col_integer(),
      Ma_LF_C52 = col_integer(),
      Ma_LF_C53 = col_integer(),
      Ma_LF_C54 = col_integer(),
      Ma_LF_D01 = col_integer(),
      Ma_LF_D01_SPCY = col_character(),
      Ma_LF_D02 = col_integer(),
      Ma_LF_D02_SPCFY = col_character()
    )
  }

  if (ins == "sf" && type == "adaptive") {
    spec <- cols(
      GSED_ID = col_character(),
      parent_study_id = col_character(),
      Ma_SF_DOB = col_date(format = date_format),
      Ma_SF_DOV = col_date(format = date_format),
      Ma_SF_Location = col_integer(),
      Ma_Age_Year = col_double(),
      Ma_SF_item = col_character(),
      Ma_SF_timestamp = col_datetime(format = datetime_format),
      p = col_integer(),
      Ma_SF_order = col_integer(),
      Ma_SF_scores = col_integer(),
      Ma_SF_d = col_double(),
      Ma_SF_sem = col_double()
    )
  }

  if (ins == "lf" && type == "adaptive") {
    spec <- cols(
      GSED_ID = col_character(),
      parent_study_id = col_character(),
      Ma_LF_DOB = col_date(format = date_format),
      Ma_LF_DOV = col_date(format = date_format),
      Ma_LF_Location = col_integer(),
      Ma_Age_Year = col_double(),
      Ma_LF_item = col_character(),
      Ma_LF_timestamp = col_datetime(format = datetime_format),
      p = col_integer(),
      Ma_LF_order = col_integer(),
      Ma_LF_scores = col_integer(),
      Ma_LF_d = col_double(),
      Ma_LF_sem = col_double()
    )
  }

  return(spec)
}


