#' Define column types for data reading
#'
#' @param ins Character, the instrument
#' @param form Character, fixed or adaptive
#' @param date_format Specification how to read the date field
#' @param datetime_format Specification how to read the datetime field
#' @export
define_col_type <- function(ins = c("sf", "lf"),
                            form = c("fixed", "adaptive"),
                            date_format = "",
                            datetime_format = "") {
  ins <- match.arg(ins)
  form <- match.arg(form)
  if (ins == "sf" && form == "fixed") {
    spec <- cols(
      GSED_ID = col_character(),
      `Ma_SF_Parent ID` = col_character(),
      `Ma_SF_Worker Code` = col_double(),
      `Ma_SF_Vist Type` = col_double(),
      Ma_SF_Location = col_double(),
      Ma_SF_Age = col_double(),
      Ma_SF_AH01 = col_double(),
      Ma_SF_AH02 = col_double(),
      Ma_SF_AH03 = col_double(),
      Ma_SF_AH04 = col_double(),
      Ma_SF_AH05 = col_double(),
      Ma_SF_AH06 = col_double(),
      Ma_SF_AH07 = col_double(),
      Ma_SF_AH08 = col_double(),
      Ma_SF_M01 = col_double(),
      Ma_SF_M02 = col_double(),
      Ma_SF_M03 = col_character(),
      Ma_SF_Date = col_date(format = date_format),
      Ma_SF_Caregiver = col_double(),
      Ma_SF_C01 = col_integer(),
      Ma_SF_C02 = col_integer(),
      Ma_SF_C03 = col_integer(),
      Ma_SF_C04 = col_integer(),
      Ma_SF_C05 = col_integer(),
      Ma_SF_C06 = col_integer(),
      Ma_SF_C07 = col_integer(),
      Ma_SF_C08 = col_integer(),
      Ma_SF_C09 = col_integer(),
      Ma_SF_C10 = col_integer(),
      Ma_SF_C11 = col_integer(),
      Ma_SF_C12 = col_integer(),
      Ma_SF_C13 = col_integer(),
      Ma_SF_C14 = col_integer(),
      Ma_SF_C15 = col_integer(),
      Ma_SF_C16 = col_integer(),
      Ma_SF_C17 = col_integer(),
      Ma_SF_C18 = col_integer(),
      Ma_SF_C19 = col_integer(),
      Ma_SF_C20 = col_integer(),
      Ma_SF_C21 = col_integer(),
      Ma_SF_C22 = col_integer(),
      Ma_SF_C23 = col_integer(),
      Ma_SF_C24 = col_integer(),
      Ma_SF_C25 = col_integer(),
      Ma_SF_C26 = col_integer(),
      Ma_SF_C27 = col_integer(),
      Ma_SF_C28 = col_integer(),
      Ma_SF_C29 = col_integer(),
      Ma_SF_C30 = col_integer(),
      Ma_SF_C31 = col_integer(),
      Ma_SF_C32 = col_integer(),
      Ma_SF_C33 = col_integer(),
      Ma_SF_C34 = col_integer(),
      Ma_SF_C35 = col_integer(),
      Ma_SF_C36 = col_integer(),
      Ma_SF_C37 = col_integer(),
      Ma_SF_C38 = col_integer(),
      Ma_SF_C39 = col_integer(),
      Ma_SF_C40 = col_integer(),
      Ma_SF_C41 = col_integer(),
      Ma_SF_C42 = col_integer(),
      Ma_SF_C43 = col_integer(),
      Ma_SF_C44 = col_integer(),
      Ma_SF_C45 = col_integer(),
      Ma_SF_C46 = col_integer(),
      Ma_SF_C47 = col_integer(),
      Ma_SF_C48 = col_integer(),
      Ma_SF_C49 = col_integer(),
      Ma_SF_C50 = col_integer(),
      Ma_SF_C51 = col_integer(),
      Ma_SF_C52 = col_integer(),
      Ma_SF_C53 = col_integer(),
      Ma_SF_C54 = col_integer(),
      Ma_SF_C55 = col_integer(),
      Ma_SF_C56 = col_integer(),
      Ma_SF_C57 = col_integer(),
      Ma_SF_C58 = col_integer(),
      Ma_SF_C59 = col_integer(),
      Ma_SF_C60 = col_integer(),
      Ma_SF_C61 = col_integer(),
      Ma_SF_C62 = col_integer(),
      Ma_SF_C63 = col_integer(),
      Ma_SF_C64 = col_integer(),
      Ma_SF_C65 = col_integer(),
      Ma_SF_C66 = col_integer(),
      Ma_SF_C67 = col_integer(),
      Ma_SF_C68 = col_integer(),
      Ma_SF_C69 = col_integer(),
      Ma_SF_C70 = col_integer(),
      Ma_SF_C71 = col_integer(),
      Ma_SF_C72 = col_integer(),
      Ma_SF_C73 = col_integer(),
      Ma_SF_C74 = col_integer(),
      Ma_SF_C75 = col_integer(),
      Ma_SF_C76 = col_integer(),
      Ma_SF_C77 = col_integer(),
      Ma_SF_C78 = col_integer(),
      Ma_SF_C79 = col_integer(),
      Ma_SF_C80 = col_integer(),
      Ma_SF_C81 = col_integer(),
      Ma_SF_C82 = col_integer(),
      Ma_SF_C83 = col_integer(),
      Ma_SF_C84 = col_integer(),
      Ma_SF_C85 = col_integer(),
      Ma_SF_C86 = col_integer(),
      Ma_SF_C87 = col_integer(),
      Ma_SF_C88 = col_integer(),
      Ma_SF_C89 = col_integer(),
      Ma_SF_C90 = col_integer(),
      Ma_SF_C91 = col_integer(),
      Ma_SF_C92 = col_integer(),
      Ma_SF_C93 = col_integer(),
      Ma_SF_C94 = col_integer(),
      Ma_SF_C95 = col_integer(),
      Ma_SF_C96 = col_integer(),
      Ma_SF_C97 = col_integer(),
      Ma_SF_C98 = col_integer(),
      Ma_SF_C99 = col_integer(),
      Ma_SF_C100 = col_integer(),
      Ma_SF_C101 = col_integer(),
      Ma_SF_C102 = col_integer(),
      Ma_SF_C103 = col_integer(),
      Ma_SF_C104 = col_integer(),
      Ma_SF_C105 = col_integer(),
      Ma_SF_C106 = col_integer(),
      Ma_SF_C107 = col_integer(),
      Ma_SF_C108 = col_integer(),
      Ma_SF_C109 = col_integer(),
      Ma_SF_C110 = col_integer(),
      Ma_SF_C111 = col_integer(),
      Ma_SF_C112 = col_integer(),
      Ma_SF_C113 = col_integer(),
      Ma_SF_C114 = col_integer(),
      Ma_SF_C115 = col_integer(),
      Ma_SF_C116 = col_integer(),
      Ma_SF_C117 = col_integer(),
      Ma_SF_C118 = col_integer(),
      Ma_SF_C119 = col_integer(),
      Ma_SF_C120 = col_integer(),
      Ma_SF_C121 = col_integer(),
      Ma_SF_C122 = col_integer(),
      Ma_SF_C123 = col_integer(),
      Ma_SF_C124 = col_integer(),
      Ma_SF_C125 = col_integer(),
      Ma_SF_C126 = col_integer(),
      Ma_SF_C127 = col_integer(),
      Ma_SF_C128 = col_integer(),
      Ma_SF_C129 = col_integer(),
      Ma_SF_C130 = col_integer(),
      Ma_SF_C131 = col_integer(),
      Ma_SF_C132 = col_integer(),
      Ma_SF_C133 = col_integer(),
      Ma_SF_C134 = col_integer(),
      Ma_SF_C135 = col_integer(),
      Ma_SF_C136 = col_integer(),
      Ma_SF_C137 = col_integer(),
      Ma_SF_C138 = col_integer(),
      Ma_SF_C139 = col_integer())
  }

  if (ins == "sf" && form == "adaptive") {
  spec <- cols(
      GSED_ID = col_character(),
      parent_study_id = col_character(),
      Ma_SF_DOB = col_date(format = date_format),
      Ma_SF_DOV = col_date(format = date_format),
      Ma_SF_Location = col_integer(),
      Ma_Age_Year = col_double(),
      Ma_SF_item = col_character(),
      Ma_SF_timestamp = col_datetime(format = datetime_format),
      p = col_integer(),
      Ma_SF_order = col_integer(),
      Ma_SF_scores = col_integer(),
      Ma_SF_d = col_double(),
      Ma_SF_sem = col_double()
    )
  }
  spec
}

